name: Economy
version: '1.0'
main: dev.endless.v4.economy.Main
api-version: '1.21'
authors: [ Endless v4 ]
description: Custom economy system made for Chunkverse.
softdepend: [PlaceholderAPI]
commands:
  orbsa:
    description: Manage the premium currency for players.
  bitsa:
    description: Manage the general currency for players.
  orbs:
    description: Check/send orbs.
  bits:
    description: Check/send bits.
  orbaccept:
    description: Accepting the sending of premium currency.
  orbdeny:
    description: Cancelling the sending of premium currency.
  openlogs:
    description: Open the logs.

permissions:
  chunkverse.economy.logs:
    description: Allows the player to open the logs in the form of a book.
  chunkverse.bits.give:
    description: Allows the player to give bits.
  chunkverse.bits.take:
    description: Allows the player to take bits.
  chunkverse.bits.set:
    description: Allows the player to set bits.
  chunkverse.bits.reset:
    description: Allows the player to reset bits.
  chunkverse.orbs.give:
    description: Allows the player to give orbs.
  chunkverse.orbs.take:
    description: Allows the player to take orbs.
  chunkverse.orbs.set:
    description: Allows the player to set orbs.
  chunkverse.orbs.reset:
    description: Allows the player to reset orbs.